### ISSUE TITLE
Update documentation with dependencies and examples

### ISSUE THREAD

**Issue by mmalmeid** [up2metric/cam2lidar#2]
Hi, I've been trying to instal this package to test. I had to install a few more packages. I would suggest adding them to the documentation:
```
pip install apriltag PySide6 scikit-learn open3d scikit-spatial scikit-image
```

In addition, I couldn't find the dependency for `img_to_grid`. Is this code that you have developed or is it part of a third party package? 

Also, it would be nice to add a sample Rosbag that we can use to test your example. That could be helpful in allowing us to find insights in case our application doesn't work

**Comment by mmalmeid** [comment]
The issue with `img_to_grid` exists within the docker as well.

It was a big pain to actually run things in docker, as it was stubbornly using `python-dateutil` 2.7.3, which is not compatible with the latest version of `open3d`.
I had to uninstall it using `sudo pip uninstall python-dateutil --isolated` and then install the right version `pip install python-dateutil==2.8.2`

**Comment by hirenpatel1207** [comment]
Where you able to solve the ´img_to_grid´ dependency issue?

**Comment by marcelinomalmeidan** [comment]
nope =/

**Comment by Surajj4837-th** [comment]
If someone has resolved this then kindly post the solution.

**Comment by monikaskawka** [comment]
Hi, we have added the `img_to_grid` file in the new release. The issue should be resolved.
