### ISSUE TITLE
ModuleNotFoundError: No module named 'img_to_grid'

### ISSUE THREAD

**Issue by Surajj4837-th** [up2metric/cam2lidar#3]
I was trying to execute this repository, I'm getting the following error:
`ModuleNotFoundError: No module named 'img_to_grid'`

Kindly provide the **img_to_grid** file.

I think the following functions are from img_to_grid module:
1. Image
2. generate_sections
3. generate_crop_coordinates
4. generate_subimages

If sharing of module is not possible then please inform the resource or logic to replace the missing functions.

@anastasispk Need your guidance on this issue.

**Comment by monikaskawka** [comment]
Hi, we have added the `img_to_grid` file in the new release. The issue should be resolved.
