### ISSUE TITLE
I did not understand parameter

### ISSUE THREAD

**Issue by ahmetyuce526** [up2metric/cam2lidar#5]
in the config parameter , you are telling , write these   # Geometric calibration
reproj_error: 8
intensity_thres: 200
distance_from_prev: 100
horizontal_dimension: 1920
vertical_dimension: 1080
grid_horizontal_division: 5
grid_vertical_division: 5

I think you have to little bit explain more I dont know where I find these  value  for example  (grid_horizontal_division/grid_vertical_division: Shape of grid, in order to have one measurement per rectangle) , I did not understand anything about that , I am outsider of cv field. How can I measure or find. 
and I also get this  error  " File "/opt/ros/noetic/lib/python3/dist-packages/rospy/service.py", line 116, in register
    raise ServiceException(err)
rospy.service.ServiceException: service [/parameters_set] already registered
Traceback (most recent call last):
  File "/root/catkin_ws/src/cam2lidar/src/user_interface.py", line 62, in calibrate
"  
and this "tmp/pip-install-nn5gewsb/apriltag/core/contrib/apriltag_quad_contour.c:467: warning: count < 8 :(
"

**Comment by monikaskawka** [comment]
Hello @ahmetyuce526,

The `grid_horizontal_division/grid_vertical_division` parameters divide the image into a (grid_horizontal_division) x (grid_vertical_division) grid. If you would like to find out more about the implemented algorithm, you can read our paper, [An Effective Camera-to-Lidar Spatiotemporal Calibration Based on a Simple Calibration Target [pdf]](https://www.mdpi.com/1424-8220/22/15/5576/pdf?version=1658889926).

The `rospy.service.ServiceException` usually appears when you attempt to modify the `Distance Threshold` and `Consequent Frame` parameters via the user interface after clicking the `Start` button. To begin the procedure, you must first select the `Distance Threshold` and `Consequent Frame` parameters and then click `Start`.
