### ISSUE TITLE
Link to sample rosbag does not work

### ISSUE THREAD

**Issue by ManuelFraunhofer** [up2metric/cam2lidar#7]
Hello, 

thank you very much for your recent update! So we got your software starting now.
As we did not succeed yet with our own sensor data, we would like to use your sample rosbag to see how a successful calibration should look like.
In your README.md you have a link to a sample rosbag:
https://filebrowser.homelab.up2metric.com/share/J1vaDI4Z

Clicking this link sais:
This location can't be reached.

Could you fix this link, or somehow else provide your sample rosbag?

Thank you very much
   Manuel from Fraunhofer

**Comment by cstent** [comment]
Please use the following link

https://filebrowser.homelab.up2metric.com/share/JJw-BnDA

Regards,
Christos.

**Comment by ManuelFraunhofer** [comment]
Thanks for the link fix, and the file. 
I could do a successful geometric calibration with your rosbag.
